### PR TITLE
include upstream fix

### PR DESCRIPTION
**Pull request by casperdcl**
- [x] blocked on upstream release

### CODE REVIEW

**Comment by casperdcl** [comment]
Sorry for the delay; should work now :)

**Comment by casperdcl** [comment]
actually still not fixed, only [v0.18.20](https://github.com/iterative/cml/releases/tag/v0.18.20) has been fixed. Still waiting for v0.18.21 :/

**Comment by casperdcl** [comment]
https://github.com/iterative/cml/releases/tag/v0.18.21 released (finally)!

**Comment by cameronraysmith** [comment]
Thank you @casperdcl ! 

I'm depending on the version coming through the Docker images so I will trigger a rebuild and test when I [see they've been updated](https://github.com/iterative/cml/pkgs/container/cml) or manually upgrade cml to the latest version.

**Pull request merged**
